/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventanas;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edward
 */
public class Laboratorio extends javax.swing.JFrame {

    private String Tipo = "";
    private Clip clip;
    private String path="/Audio/";
    
    ventanas.Conector cc = new ventanas.Conector();
    Connection cn = cc.conexion();
    
    /**
     * Creates new form Laboratorio
     */
    public Laboratorio() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        actualizar();
        
    }

    
     public void sonido(String value)
    {        
       try
       {
   clip=AudioSystem.getClip();
   clip.open(AudioSystem.getAudioInputStream( getClass().getResourceAsStream( path +  value +".wav" ) ) );
          clip.start();
       }catch(Exception ex){
    System.err.println( ex.getMessage() );
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        code = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        disp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Laboratorio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/Iconos/panel-del-menu-de-la-ventana-icono-6573-32 - copia.png"))); // NOI18N
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 112, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 269, 382));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/Iconos/add.png"))); // NOI18N
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 170, 40));

        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codeKeyTyped(evt);
            }
        });
        getContentPane().add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/Iconos/edit.png"))); // NOI18N
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 170, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/Iconos/del.png"))); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 170, 40));

        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setText("Disponible?:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        disp.setToolTipText("si/no");
        disp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dispKeyTyped(evt);
            }
        });
        getContentPane().add(disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 200, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/Iconos/lab.png"))); // NOI18N
        jLabel3.setText("Laboratorios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/Iconos/borra.png"))); // NOI18N
        jButton5.setText("Borrar campos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 170, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/Iconos/exit.png"))); // NOI18N
        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 110, 40));

        jButton7.setText("exportar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sonido("mous");
        dispose();
        Menu men1=new Menu();
        men1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

  
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

     
         if(code.getText().equals("") || disp.getText().equals("")){JOptionPane.showMessageDialog(null,"Hay campos vacios");
          }else{
             
         
        
        String Codigo,Disponible;

        Codigo=code.getText();
        Disponible=disp.getText();
      
      

        ResultSet rs;
        
        Statement  stmt = null;

        try {
            

            stmt = cn.createStatement();
          
            //Aqui verifica si existe
            rs = stmt.executeQuery("SELECT * FROM Laboratorios WHERE `laboratorio`='" + Codigo + "'");
           
            if(!rs.next()){
            stmt.executeUpdate("INSERT INTO Laboratorios VALUES ( '" + Codigo + "','" + Disponible + "')");
            
            
            sonido("bleep");
             JOptionPane.showMessageDialog(null,"Se agregó la informacion exitosamente");
             
            }else{ JOptionPane.showMessageDialog(null,"ya existe");}
             
            System.out.println("Los valores han sido agregados a la base de datos ");
        }
        catch( SQLException e ) {
            e.printStackTrace();
        }

       
        
       code.setText("");
       disp.setText("");
       
        actualizar();
        
        
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
               if(code.getText().equals("") || disp.getText().equals("")){JOptionPane.showMessageDialog(null,"Selecciona un elemento de la tabla");
          }else{
        
        DefaultTableModel modelo= (DefaultTableModel)jTable1.getModel();
        //Selecciona el valor de la columna 1
        String valor1= String.valueOf(modelo.getValueAt(jTable1.getSelectedRow(),0));
      
        
        sonido("error");
        
      
        
        int x = JOptionPane.showConfirmDialog(null,"¿Estas seguro de eliminar?","Confirmar",JOptionPane.YES_NO_OPTION);
        if( x == JOptionPane.YES_OPTION){
             sonido("bleep");
            
        
        Connection con = null;
        Statement  stmt = null;

        try {
            String url = "jdbc:mysql://localhost:3306/sistema";
            String usuario = "root";
            String contrasena = "123";
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
            } catch (InstantiationException ex) {
                Logger.getLogger(Laboratorio.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Laboratorio.class.getName()).log(Level.SEVERE, null, ex);
            }

            con = DriverManager.getConnection(url,usuario,contrasena);
            if ( con != null )
            System.out.println("Se ha establecido una conexión a la base de datos " +
                "\n " + url );
            stmt = con.createStatement();
            
            stmt.executeUpdate("DELETE FROM `Laboratorios` WHERE (`laboratorio`='" + valor1 + "')");
            
        }
        catch( SQLException e ) {
            e.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Laboratorio.class.getName()).log(Level.SEVERE, null, ex);
        }

        finally {
            if ( con != null ) {
                try    {
                    con.close();
                    stmt.close();
                } catch( Exception e ) {
                    System.out.println( e.getMessage());
                }
            }
        }
        JOptionPane.showMessageDialog(null,"Se eliminó la informacion exitosamente");
        actualizar();
        code.setText("");
        disp.setText("");
        }
               }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           if(code.getText().equals("") || disp.getText().equals("")){JOptionPane.showMessageDialog(null,"Selecciona un elemento de la tabla");
          }else{
        
        DefaultTableModel modelo= (DefaultTableModel)jTable1.getModel();
        //Selecciona el valor de la columna 1
        String valor1= String.valueOf(modelo.getValueAt(jTable1.getSelectedRow(),0));
        
         sonido("error");
         
        int x = JOptionPane.showConfirmDialog(null,"¿Estas seguro de editar?","Confirmar",JOptionPane.YES_NO_OPTION);
        if( x == JOptionPane.YES_OPTION){  
            sonido("bleep");
        JOptionPane.showMessageDialog(null,"Se editó exitosamente");
      
       
        String Disponible,Laboratory;

        Laboratory=code.getText();
        Disponible=disp.getText();

        Statement  stmt = null;

        try {
            

            stmt = cn.createStatement();
            stmt.executeUpdate("UPDATE Laboratorios set `laboratorio`='"+Laboratory+"',`disponible`='"+Disponible+"' WHERE( `laboratorio`='"+valor1+ "')");

            System.out.println("Los valores han sido agregados a la base de datos ");
        }
        catch( SQLException e ) {
            e.printStackTrace();
        }

       
        
        actualizar();
       }
        
       code.setText("");
       disp.setText("");
       
           }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_DELETE){
           DefaultTableModel modelo= (DefaultTableModel)jTable1.getModel();
        //Selecciona el valor de la columna 1
        String valor1= String.valueOf(modelo.getValueAt(jTable1.getSelectedRow(),0));
      
        
        sonido("error");
        
      
        
        int x = JOptionPane.showConfirmDialog(null,"¿Estas seguro de eliminar?","Confirmar",JOptionPane.YES_NO_OPTION);
        if( x == JOptionPane.YES_OPTION){
             sonido("bleep");
            
        
        Connection con = null;
        Statement  stmt = null;

        try {
            String url = "jdbc:mysql://localhost:3306/sistema";
            String usuario = "root";
            String contrasena = "123";
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
            } catch (InstantiationException ex) {
                Logger.getLogger(Laboratorio.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Laboratorio.class.getName()).log(Level.SEVERE, null, ex);
            }

            con = DriverManager.getConnection(url,usuario,contrasena);
            if ( con != null )
            System.out.println("Se ha establecido una conexión a la base de datos " +
                "\n " + url );
            stmt = con.createStatement();
            
            stmt.executeUpdate("DELETE FROM `Laboratorios` WHERE (`laboratorio`='" + valor1 + "')");
            
        }
        catch( SQLException e ) {
            e.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Laboratorio.class.getName()).log(Level.SEVERE, null, ex);
        }

        finally {
            if ( con != null ) {
                try    {
                    con.close();
                    stmt.close();
                } catch( Exception e ) {
                    System.out.println( e.getMessage());
                }
            }
        }
        JOptionPane.showMessageDialog(null,"Se eliminó la informacion exitosamente");
        actualizar();
        }
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        code.setText("");
        disp.setText("");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      int row = jTable1.getSelectedRow();
      String id=jTable1.getValueAt(row, 0).toString();
      String disponible=jTable1.getValueAt(row, 1).toString();
     
      code.setText(id);
      disp.setText(disponible);
     
    }//GEN-LAST:event_jTable1MouseClicked

    private void dispKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dispKeyTyped
       String s1=String.valueOf(evt.getKeyChar());
        
        if(!(s1.matches("[a-z A-Z]"))){
        evt.consume();
        getToolkit().beep();
        }    
    }//GEN-LAST:event_dispKeyTyped

    private void codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeKeyTyped
        String s1=String.valueOf(evt.getKeyChar());
        
        if(!(s1.matches("[0-9]"))){
        evt.consume();
        getToolkit().beep();
        }    
    }//GEN-LAST:event_codeKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         sonido("error");
        int x = JOptionPane.showConfirmDialog(null,"¿Deseas salir del programa?","Confirmar",JOptionPane.YES_NO_OPTION);
        if( x == JOptionPane.YES_OPTION){
            sonido("bleep");
            dispose();

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       example export=new example();
       export.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    
    
     public void actualizar(){
    String sql = "select * from laboratorios";
    DefaultTableModel model = new DefaultTableModel();
    try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            ResultSetMetaData metadata = rs.getMetaData();   
            while(rs.next()){ 
               int cantidadColumnas = metadata.getColumnCount();
            for (int i = 1; i <= cantidadColumnas; i++) {
                model.addColumn(metadata.getColumnLabel(i));
            }while (rs.next()) {
                Object[] fila = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i]=rs.getObject(i+1);
                }model.addRow(fila);
            }
            }jTable1.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laboratorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JTextField disp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
